package com.restapi.Restfull.API.Server.response;

public class ResMessage {
    public static final String TEST_SUCCESS = "The Test is successfully complete";
    public static final String INTERNAL_SERVER_ERROR = "Internal Server error";
    public static final String INTERNAL_DATABASE_ERROR = "Internal Database error";
    public static final String FILE_IS_EMPTY = "File is empty for request";
    public static final String FILE_TYPE_UNSUPPORTED = "File type is not support";
    public static final String FILE_UPLOAD_SUCCESS = "File upload is success";
    public static final String MULTIPLE_FILE_UPLOAD_SUCCESS = "Multiple file upload is success";
    public static final String TEST_FAILED = "The Test is failed";
    public static final String LOGIN_SUCCESS = "User Login is successful";
    public static final String WITHDRAW_SUCCESS = "User Deleted successfully";
    public static final String USER_INFO_ACCESS = "Getting User Info";
    public static final String ARTIST_REGISTER_SUCCESS = "Artist Registered Successfully";
    public static final String ALREADY_REGISTERED_ARTIST = "Already registered Artist";
    public static final String ARTIST_NAME_IN_USE = "Artist name is in use";
    public static final String ARTIST_INFO_CALL_SUCCESS = "Artist Info Response success";
    public static final String SUBSCRIBE_SUCCESS = "Subscribe is success";
    public static final String UNDO_SUBSCRIBE_SUCCESS = "Subscribe delete success";
    public static final String CANNOT_SUBSCRIBE_YOURSELF = "You can't subscribe yourself";
    public static final String ARTIST_SPON_SUCCESS = "Artist Spon Success";
    public static final String BOARD_SPON_SUCCESS = "Board Spon Success";
    public static final String GET_PORTFOLIO_SUCCESS = "Getting Portfolio";
    public static final String GET_BOARD_SUCCESS = "Getting Board";
    public static final String GET_BOARD_LIST_SUCCESS = "Getting Board List";
    public static final String LIKE_PORTFOLIO_SUCCESS = "Portfolio Like Success";
    public static final String UNDO_LIKE_PORTFOLIO_SUCCESS = "delete Portfolio Like Success";
    public static final String LIKE_BOARD_SUCCESS = "Board Like Success";
    public static final String UNDO_LIKE_BOARD_SUCCESS = "delete Board Like Success";
    public static final String PORTFOLIO_COMMENT_INSERT_SUCCESS = "Insert Portfolio Comment Success";
    public static final String PORTFOLIO_COMMENT_DELETE_SUCCESS = "Delete Portfolio Comment Success";
    public static final String BOARD_COMMENT_INSERT_SUCCESS = "Insert Board Comment Success";
    public static final String BOARD_COMMENT_DELETE_SUCCESS = "Delete Board Comment Success";
    public static final String EDIT_PORTFOLIO_SUCCESS = "Portfolio Edit Success";
    public static final String EDIT_BOARD_SUCCESS = "Board Edit Success";
    public static final String UPLOAD_PORTFOLIO_SUCCESS = "Portfolio Upload Success";
    public static final String DELETE_PORTFOLIO_SUCCESS = "Portfolio Delete Success";
    public static final String UPLOAD_BOARD_SUCCESS = "Board Upload Success";
    public static final String DELETE_BOARD_SUCCESS = "Board Delete Success";
    public static final String FILE_TYPE_MISMATCH = "File type doesn't match with Portfolio Type";
    public static final String PORTFOLIO_TYPE_ERROR = "Portfolio Type Error";
    public static final String NO_USER_DETECTED = "No User in given user_no";
    public static final String CANNOT_SPON_YOURSELF = "User and Artist are same";
    public static final String CHECK_USER_PRIVATE_SUCCESS = "Checking User Private Success";
    public static final String NOT_SUBSCRIBED_ARTIST = "not Subscribe Artist";
    public static final String VOD_LIST_CALL_SUCCESS = "Getting VOD List";
}
